name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Select option '...'
        3. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages if any.
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: yt Version
      description: Run `yt` with no arguments to see the version
      placeholder: "1.0.0"
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (Arch)
        - Linux (Fedora/RHEL)
        - Other
    validations:
      required: true
  
  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: "macOS 14.0, Ubuntu 22.04, etc."
  
  - type: textarea
    id: dependencies
    attributes:
      label: Dependency Versions
      description: Run the following commands and paste the output
      placeholder: |
        yt-dlp --version
        mpv --version
        fzf --version
        jq --version
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)
